# Generated by Django 6.0.3 on 2026-05-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trình độ học vấn',
                'verbose_name_plural': 'Trình độ học vấn',
                'db_table': 'ref_education_levels',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dân tộc',
                'verbose_name_plural': 'Dân tộc',
                'db_table': 'ref_ethnic_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Trình độ chính trị',
                'verbose_name_plural': 'Trình độ chính trị',
                'db_table': 'ref_political_levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tôn giáo',
                'verbose_name_plural': 'Tôn giáo',
                'db_table': 'ref_religions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('province', 'Tỉnh/Thành phố'), ('district', 'Huyện/Quận'), ('ward', 'Xã/Phường/Thị trấn'), ('hamlet', 'Ấp/Thôn/Bản')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.administrativeunit')),
            ],
            options={
                'verbose_name': 'Đơn vị hành chính',
                'verbose_name_plural': 'Đơn vị hành chính',
                'db_table': 'ref_administrative_units',
                'indexes': [models.Index(fields=['parent_id'], name='ref_adminis_parent__78449b_idx'), models.Index(fields=['type'], name='ref_adminis_type_870086_idx')],
            },
        ),
    ]
