# Generated by Django 6.0.3 on 2026-05-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('zalo_oa', 'Zalo OA'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'Trong ứng dụng')], max_length=20)),
                ('type', models.CharField(choices=[('account_created', 'Tạo tài khoản'), ('profile_submitted', 'Nộp hồ sơ'), ('profile_approved', 'Phê duyệt hồ sơ'), ('profile_returned', 'Trả lại hồ sơ'), ('profile_rejected', 'Từ chối hồ sơ'), ('profile_completed', 'Hoàn thiện hồ sơ'), ('verification_sent', 'Gửi xác minh'), ('verification_reminder', 'Nhắc xác minh'), ('verification_received', 'Nhận kết quả xác minh'), ('ai_issue_detected', 'AI phát hiện vấn đề'), ('correction_request', 'Yêu cầu bổ sung'), ('correction_resolved', 'Đã bổ sung'), ('bulk_reminder', 'Nhắc hàng loạt'), ('system_alert', 'Cảnh báo hệ thống'), ('custom', 'Tùy chỉnh')], max_length=40)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_status', models.CharField(choices=[('pending', 'Chờ gửi'), ('sending', 'Đang gửi'), ('sent', 'Đã gửi'), ('delivered', 'Đã nhận'), ('failed', 'Thất bại'), ('bounced', 'Bị trả về')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('zalo_oa', 'Zalo OA'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'Trong ứng dụng')], max_length=20)),
                ('type', models.CharField(max_length=80)),
                ('recipient_filter', models.JSONField(blank=True, null=True)),
                ('custom_body', models.TextField(blank=True, null=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('sending', 'Đang gửi'), ('completed', 'Hoàn tất'), ('failed', 'Thất bại')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Đợt gửi thông báo',
                'verbose_name_plural': 'Đợt gửi thông báo',
                'db_table': 'notification_batches',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('zalo_oa', 'Zalo OA'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'Trong ứng dụng')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(help_text='Hỗ trợ {{variable}} placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mẫu thông báo',
                'verbose_name_plural': 'Mẫu thông báo',
                'db_table': 'notification_templates',
            },
        ),
    ]
