# Generated by Django 6.0.3 on 2026-05-12 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCorrectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=80)),
                ('field_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ bổ sung'), ('corrected', 'Đã bổ sung'), ('waived', 'Bỏ qua')], default='pending', max_length=20)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mục yêu cầu bổ sung',
                'verbose_name_plural': 'Mục yêu cầu bổ sung',
                'db_table': 'profile_correction_items',
            },
        ),
        migrations.CreateModel(
            name='ProfileEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=80)),
                ('field_name', models.CharField(max_length=120)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('edit_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử chỉnh sửa',
                'verbose_name_plural': 'Lịch sử chỉnh sửa',
                'db_table': 'profile_edit_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=120, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('sections_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xuất Word',
                'verbose_name_plural': 'Xuất Word',
                'db_table': 'word_export_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Chờ bổ sung'), ('in_progress', 'Đang bổ sung'), ('resolved', 'Đã bổ sung'), ('dismissed', 'Đã đóng')], default='open', max_length=20)),
                ('overall_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu bổ sung',
                'verbose_name_plural': 'Yêu cầu bổ sung',
                'db_table': 'profile_correction_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
