# Generated by Django 6.0.3 on 2026-05-12 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exports', '0001_initial'),
        ('profiles', '0001_initial'),
        ('uploads', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecorrectionrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profilecorrectionrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_column='resolved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilecorrectionitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exports.profilecorrectionrequest'),
        ),
        migrations.AddField(
            model_name='profileedithistory',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileedithistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='wordexportlog',
            name='exported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordexportlog',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_export_logs', to='uploads.uploadedfile'),
        ),
        migrations.AddField(
            model_name='wordexportlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_exports', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='profilecorrectionrequest',
            index=models.Index(fields=['profile', 'status'], name='profile_cor_profile_3f9de4_idx'),
        ),
        migrations.AddIndex(
            model_name='profileedithistory',
            index=models.Index(fields=['profile', '-created_at'], name='profile_edi_profile_729a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='profileedithistory',
            index=models.Index(fields=['section'], name='profile_edi_section_d37782_idx'),
        ),
    ]
