# Generated by Django 6.0.3 on 2026-05-12 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('view', 'Xem'), ('export', 'Xuất'), ('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('approve', 'Duyệt'), ('reject', 'Từ chối'), ('submit', 'Nộp'), ('send', 'Gửi')], max_length=20)),
                ('target_model', models.CharField(blank=True, max_length=80, null=True)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'), models.Index(fields=['target_model', 'target_id'], name='activity_lo_target__23e139_idx'), models.Index(fields=['action'], name='activity_lo_action_b49f28_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=80)),
                ('field_name', models.CharField(blank=True, max_length=120, null=True)),
                ('issue_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('error', 'Lỗi')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Chưa xử lý'), ('resolved', 'Đã xử lý'), ('ignored', 'Bỏ qua')], default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scan_results', to='profiles.profile')),
                ('resolved_by', models.ForeignKey(blank=True, db_column='resolved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ai_scans', to=settings.AUTH_USER_MODEL)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kết quả quét AI',
                'verbose_name_plural': 'Kết quả quét AI',
                'db_table': 'ai_scan_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='ai_scan_res_profile_e104ac_idx'), models.Index(fields=['severity'], name='ai_scan_res_severit_1d88d5_idx')],
            },
        ),
    ]
