# Generated by Django 6.0.3 on 2026-05-12 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('uploads', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=500)),
                ('agency_contact', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('urgency', models.CharField(choices=[('normal', 'Thường'), ('urgent', 'Khẩn'), ('critical', 'Rất khẩn')], default='normal', max_length=20)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Chưa gửi'), ('pending', 'Chờ phản hồi'), ('received', 'Đã nhận kết quả'), ('completed', 'Hoàn tất'), ('overdue', 'Quá hạn'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_verifications', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='profiles.profile')),
                ('result_file', models.ForeignKey(blank=True, db_column='result_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_results', to='uploads.uploadedfile')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu xác minh',
                'verbose_name_plural': 'Yêu cầu xác minh',
                'db_table': 'verification_requests',
            },
        ),
        migrations.CreateModel(
            name='VerificationReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Điện thoại'), ('in_person', 'Trực tiếp'), ('other', 'Khác')], default='email', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, db_column='sent_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='verification.verificationrequest')),
            ],
            options={
                'verbose_name': 'Nhật ký nhắc xác minh',
                'verbose_name_plural': 'Nhật ký nhắc xác minh',
                'db_table': 'verification_reminder_log',
            },
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['profile', 'status'], name='verificatio_profile_eece44_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['deadline'], name='verificatio_deadlin_2b90a1_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['urgency'], name='verificatio_urgency_5efccd_idx'),
        ),
    ]
