# Generated by Django 6.0.3 on 2026-05-12 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('profile_photo', 'Ảnh hồ sơ'), ('cccd_front', 'CCCD mặt trước'), ('cccd_back', 'CCCD mặt sau'), ('certificate', 'Bằng cấp / Chứng chỉ'), ('verification_attachment', 'Tài liệu xác minh'), ('report_export', 'Xuất báo cáo'), ('word_export', 'Xuất Word/DOCX'), ('other', 'Khác')], default='other', max_length=40)),
                ('original_name', models.CharField(max_length=500)),
                ('stored_path', models.CharField(max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=127, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File đã tải lên',
                'verbose_name_plural': 'File đã tải lên',
                'db_table': 'uploaded_files',
                'indexes': [models.Index(fields=['uploader'], name='uploaded_fi_uploade_73ad0c_idx'), models.Index(fields=['category'], name='uploaded_fi_categor_bfb38e_idx')],
            },
        ),
    ]
