# Generated by Django 5.1.8 on 2026-05-25 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_accounts', models.BooleanField(default=False, verbose_name='Cấp tài khoản quần chúng')),
                ('can_review_profiles', models.BooleanField(default=False, verbose_name='Xem & trả lại hồ sơ')),
                ('can_approve_profiles', models.BooleanField(default=False, verbose_name='Phê duyệt hồ sơ')),
                ('can_export_word', models.BooleanField(default=False, verbose_name='Xuất file Word')),
                ('can_send_notifications', models.BooleanField(default=False, verbose_name='Gửi thông báo')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Xem báo cáo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân quyền cán bộ',
                'verbose_name_plural': 'Phân quyền cán bộ',
                'db_table': 'officer_permissions',
            },
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
