# Generated by Django 5.1.8 on 2026-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_officer_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='chi_bo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chi bộ'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='dang_bo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Đảng bộ'),
        ),
        migrations.AddField(
            model_name='user',
            name='chi_bo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chi bộ'),
        ),
        migrations.AddField(
            model_name='user',
            name='dang_bo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Đảng bộ'),
        ),
    ]
