# Generated by Django 6.0.3 on 2026-05-12 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Báo cáo tháng'), ('quarterly', 'Báo cáo quý'), ('annual', 'Báo cáo năm'), ('custom', 'Tùy chỉnh')], max_length=20)),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('word', 'Word')], default='excel', max_length=10)),
                ('params', models.JSONField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xuất báo cáo',
                'verbose_name_plural': 'Xuất báo cáo',
                'db_table': 'report_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatsMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('count_draft', models.IntegerField(default=0)),
                ('count_submitted', models.IntegerField(default=0)),
                ('count_under_review', models.IntegerField(default=0)),
                ('count_approved', models.IntegerField(default=0)),
                ('count_rejected', models.IntegerField(default=0)),
                ('count_archived', models.IntegerField(default=0)),
                ('count_total', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thống kê tháng',
                'verbose_name_plural': 'Thống kê tháng',
                'db_table': 'stats_monthly',
                'unique_together': {('year', 'month', 'unit_id')},
            },
        ),
    ]
