# Generated by Django 6.0.3 on 2026-05-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('cha_ruot', 'Cha ruột'), ('me_ruot', 'Mẹ ruột'), ('anh_chi_em_ruot', 'Anh/Chị/Em ruột'), ('vo_chong', 'Vợ/Chồng'), ('cha_chong_vo', 'Cha chồng/vợ'), ('me_chong_vo', 'Mẹ chồng/vợ'), ('ong_noi', 'Ông nội'), ('ba_noi', 'Bà nội'), ('ong_ngoai', 'Ông ngoại'), ('ba_ngoai', 'Bà ngoại'), ('anh_chi_em_chong_vo', 'Anh/Chị/Em chồng/vợ'), ('ong_noi_chong_vo', 'Ông nội chồng/vợ'), ('ba_noi_chong_vo', 'Bà nội chồng/vợ'), ('ong_ngoai_chong_vo', 'Ông ngoại chồng/vợ'), ('ba_ngoai_chong_vo', 'Bà ngoại chồng/vợ'), ('con', 'Con')], max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_province_text', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=500, null=True)),
                ('hometown_province_text', models.CharField(blank=True, max_length=255, null=True)),
                ('hometown', models.CharField(blank=True, max_length=500, null=True)),
                ('current_address', models.CharField(blank=True, max_length=500, null=True)),
                ('ethnic_group_text', models.CharField(blank=True, max_length=100, null=True)),
                ('religion_text', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('workplace', models.CharField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('deceased_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deceased_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('is_party_member', models.BooleanField(default=False)),
                ('party_join_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('party_chi_bo', models.CharField(blank=True, max_length=255, null=True)),
                ('party_awards_text', models.TextField(blank=True, null=True)),
                ('party_years_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('political_status', models.CharField(blank=True, max_length=255, null=True)),
                ('party_join_date', models.DateField(blank=True, null=True)),
                ('party_join_place', models.CharField(blank=True, max_length=255, null=True)),
                ('awards_disciplines', models.TextField(blank=True, null=True)),
                ('child_school', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thành viên gia đình',
                'verbose_name_plural': 'Thành viên gia đình',
                'db_table': 'family_members',
                'ordering': ['sort_order', 'relationship'],
            },
        ),
    ]
