# Generated by Django 6.0.3 on 2026-05-12 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_family_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['profile', 'relationship'], name='family_memb_profile_b70347_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['full_name'], name='family_memb_full_na_07132b_idx'),
        ),
    ]
