# Generated by Django 5.1.8 on 2026-07-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_alter_familymember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': [models.Case(models.When(relationship='cha_ruot', then=models.Value(1)), models.When(relationship='cha_duong', then=models.Value(2)), models.When(relationship='me_ruot', then=models.Value(3)), models.When(relationship='me_ke', then=models.Value(4)), models.When(relationship='anh_chi_em_ruot', then=models.Value(5)), models.When(relationship='vo_chong', then=models.Value(6)), models.When(relationship='chong_ke', then=models.Value(7)), models.When(relationship='vo_ke', then=models.Value(8)), models.When(relationship='con', then=models.Value(9)), models.When(relationship='ong_noi', then=models.Value(10)), models.When(relationship='ba_noi', then=models.Value(11)), models.When(relationship='ong_ngoai', then=models.Value(12)), models.When(relationship='ba_ngoai', then=models.Value(13)), models.When(relationship='cha_chong_vo', then=models.Value(14)), models.When(relationship='me_chong_vo', then=models.Value(15)), models.When(relationship='anh_chi_em_chong_vo', then=models.Value(16)), models.When(relationship='ong_noi_chong_vo', then=models.Value(17)), models.When(relationship='ba_noi_chong_vo', then=models.Value(18)), models.When(relationship='ong_ngoai_chong_vo', then=models.Value(19)), models.When(relationship='ba_ngoai_chong_vo', then=models.Value(20)), models.When(relationship='ong_ba_khac', then=models.Value(21)), default=models.Value(99), output_field=models.IntegerField()), 'sort_order'], 'verbose_name': 'Thành viên gia đình', 'verbose_name_plural': 'Thành viên gia đình'},
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('cha_ruot', 'Cha ruột'), ('cha_duong', 'Cha dượng'), ('me_ruot', 'Mẹ ruột'), ('me_ke', 'Mẹ kế'), ('anh_chi_em_ruot', 'Anh/Chị/Em ruột'), ('vo_chong', 'Vợ/Chồng'), ('chong_ke', 'Chồng kế'), ('vo_ke', 'Vợ kế'), ('cha_chong_vo', 'Cha chồng/vợ'), ('me_chong_vo', 'Mẹ chồng/vợ'), ('ong_noi', 'Ông nội'), ('ba_noi', 'Bà nội'), ('ong_ngoai', 'Ông ngoại'), ('ba_ngoai', 'Bà ngoại'), ('anh_chi_em_chong_vo', 'Anh/Chị/Em chồng/vợ'), ('ong_noi_chong_vo', 'Ông nội chồng/vợ'), ('ba_noi_chong_vo', 'Bà nội chồng/vợ'), ('ong_ngoai_chong_vo', 'Ông ngoại chồng/vợ'), ('ba_ngoai_chong_vo', 'Bà ngoại chồng/vợ'), ('ong_ba_khac', 'Ông/Bà khác'), ('con', 'Con')], max_length=30),
        ),
    ]
